# Generated by Django 5.0.1 on 2024-02-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('FullName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
